services:
  innovatube:
    build:
      context: .
    container_name: innovatube
    restart: unless-stopped
    init: true
    ports:
      - "8091:8091"
    networks:
      - innovatube-network
    depends_on:
      - config-server
      - eureka-server
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sasa1234
      MYSQL_DATABASE: db_personal
    ports:
      - "3306:3306"
    networks:
      - innovatube-network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  innovatube-network:
    driver: bridge
